"""rename user.nome to user.name

Revision ID: a550d76105f0
Revises: 04577540eaee
Create Date: 2026-07-26 16:31:11.463858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a550d76105f0'
down_revision: Union[str, Sequence[str], None] = '04577540eaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('users', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
